# Site settings
title: rami-portfolio
email: ramiTae@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ramitae.github.io" # the base hostname & protocol for your site

github_username: RamiTae

# Build settings
markdown: kramdown
