# Site settings
title: rami-portfolio
email: ramiTae.dev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ramitae.netlify.com" # the base hostname & protocol for your site

github_username: RamiTae
linkedIn_username: rami-tae
blog_url: https://ram-t.tistory.com/

# Build settings
markdown: kramdown
asset_url: /assets
